# Generated by Django 5.2 on 2025-05-13 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Hình ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Hình ảnh sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên tag')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag sản phẩm',
                'verbose_name_plural': 'Tags sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên biến thể')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã biến thể')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Điều chỉnh giá')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_type', models.CharField(choices=[('color', 'Màu sắc'), ('size', 'Kích thước'), ('material', 'Chất liệu'), ('style', 'Kiểu dáng'), ('other', 'Khác')], max_length=50, verbose_name='Loại thuộc tính')),
                ('value', models.CharField(max_length=100, verbose_name='Giá trị')),
            ],
            options={
                'verbose_name': 'Thuộc tính biến thể',
                'verbose_name_plural': 'Thuộc tính biến thể',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã sản phẩm')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá khuyến mãi')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Hình ảnh chính')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('featured', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Trọng lượng (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=50, verbose_name='Kích thước (DxRxC cm)')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Chất liệu')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Màu sắc')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
