# Generated by Django 5.2 on 2025-05-12 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('role', models.CharField(choices=[('manager', 'Quản lý'), ('sales', 'Nhân viên bán hàng'), ('warehouse', 'Nhân viên kho'), ('support', 'Nhân viên hỗ trợ')], max_length=20, verbose_name='Vai trò')),
                ('date_hired', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày vào làm')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Liên hệ khẩn cấp')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff/profile/', verbose_name='Ảnh đại diện')),
                ('status', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch', verbose_name='Chi nhánh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Hồ sơ nhân viên',
                'verbose_name_plural': 'Hồ sơ nhân viên',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='Kỳ đánh giá')),
                ('sales_target', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Mục tiêu doanh số')),
                ('sales_achieved', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Doanh số đạt được')),
                ('orders_processed', models.IntegerField(default=0, verbose_name='Đơn hàng đã xử lý')),
                ('customer_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Đánh giá khách hàng')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Nhận xét')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='staff.staffprofile', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Hiệu suất nhân viên',
                'verbose_name_plural': 'Hiệu suất nhân viên',
                'unique_together': {('staff', 'period')},
            },
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staff.staffprofile', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Lịch làm việc',
                'verbose_name_plural': 'Lịch làm việc',
                'unique_together': {('staff', 'date', 'start_time')},
            },
        ),
    ]
