# Generated by Django 5.2 on 2025-05-12 15:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày đánh giá')),
                ('period', models.CharField(max_length=7, verbose_name='Kỳ đánh giá')),
                ('work_quality', models.PositiveSmallIntegerField(choices=[(1, 'Kém'), (2, 'Trung bình'), (3, 'Khá'), (4, 'Tốt'), (5, 'Xuất sắc')], verbose_name='Chất lượng công việc')),
                ('work_quantity', models.PositiveSmallIntegerField(choices=[(1, 'Kém'), (2, 'Trung bình'), (3, 'Khá'), (4, 'Tốt'), (5, 'Xuất sắc')], verbose_name='Số lượng công việc')),
                ('punctuality', models.PositiveSmallIntegerField(choices=[(1, 'Kém'), (2, 'Trung bình'), (3, 'Khá'), (4, 'Tốt'), (5, 'Xuất sắc')], verbose_name='Đúng giờ')),
                ('initiative', models.PositiveSmallIntegerField(choices=[(1, 'Kém'), (2, 'Trung bình'), (3, 'Khá'), (4, 'Tốt'), (5, 'Xuất sắc')], verbose_name='Sáng kiến')),
                ('teamwork', models.PositiveSmallIntegerField(choices=[(1, 'Kém'), (2, 'Trung bình'), (3, 'Khá'), (4, 'Tốt'), (5, 'Xuất sắc')], verbose_name='Làm việc nhóm')),
                ('communication', models.PositiveSmallIntegerField(choices=[(1, 'Kém'), (2, 'Trung bình'), (3, 'Khá'), (4, 'Tốt'), (5, 'Xuất sắc')], verbose_name='Kỹ năng giao tiếp')),
                ('strengths', models.TextField(blank=True, verbose_name='Điểm mạnh')),
                ('areas_for_improvement', models.TextField(blank=True, verbose_name='Điểm cần cải thiện')),
                ('goals_for_next_period', models.TextField(blank=True, verbose_name='Mục tiêu kỳ tới')),
                ('additional_comments', models.TextField(blank=True, verbose_name='Nhận xét thêm')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Đã xác nhận')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='staff.staffprofile', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Đánh giá nhân viên',
                'verbose_name_plural': 'Đánh giá nhân viên',
                'unique_together': {('staff', 'evaluator', 'evaluation_date')},
            },
        ),
    ]
