# Generated by Django 5.2 on 2025-05-13 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền')),
                ('payment_method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('BANK_TRANSFER', 'Chuyển khoản'), ('CREDIT_CARD', 'Thẻ tín dụng'), ('MOMO', 'Ví MoMo'), ('ZALOPAY', 'ZaloPay')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('COMPLETED', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('SHIPPING', 'Đang giao hàng'), ('DELIVERED', 'Đã giao hàng'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('city', models.CharField(max_length=100, verbose_name='Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('payment_method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('BANK_TRANSFER', 'Chuyển khoản'), ('CREDIT_CARD', 'Thẻ tín dụng'), ('MOMO', 'Ví MoMo'), ('ZALOPAY', 'ZaloPay')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tạm tính')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Phí vận chuyển')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Thuế')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giảm giá')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xác nhận')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày nhận hàng')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hủy')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='branches.branch', verbose_name='Chi nhánh')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('sales_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên xử lý')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Mã vận đơn')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Đơn vị vận chuyển')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Ngày giao hàng dự kiến')),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng thực tế')),
                ('status', models.CharField(choices=[('pending', 'Chờ lấy hàng'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('failed', 'Giao hàng thất bại'), ('returned', 'Đã trả hàng')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Giao hàng',
                'verbose_name_plural': 'Giao hàng',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá bán')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Thành tiền')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
    ]
