# Generated by Django 5.2 on 2025-05-12 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('partial', 'Thanh toán một phần'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền'), ('failed', 'Thanh toán thất bại')], default='pending', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('credit_card', 'Thẻ tín dụng'), ('bank_transfer', 'Chuyển khoản'), ('paypal', 'PayPal'), ('momo', 'MoMo'), ('vnpay', 'VNPay'), ('zalopay', 'ZaloPay')], default='cash', max_length=20, verbose_name='Phương thức thanh toán')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('city', models.CharField(max_length=100, verbose_name='Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tạm tính')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Phí vận chuyển')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Thuế')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giảm giá')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số tiền đã thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày nhận hàng')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hủy')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='branches.branch', verbose_name='Chi nhánh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Mã vận đơn')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Đơn vị vận chuyển')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Ngày giao hàng dự kiến')),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng thực tế')),
                ('status', models.CharField(choices=[('pending', 'Chờ lấy hàng'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('failed', 'Giao hàng thất bại'), ('returned', 'Đã trả hàng')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Giao hàng',
                'verbose_name_plural': 'Giao hàng',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giảm giá')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='Sản phẩm')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant', verbose_name='Biến thể')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('credit_card', 'Thẻ tín dụng'), ('bank_transfer', 'Chuyển khoản'), ('paypal', 'PayPal'), ('momo', 'MoMo'), ('vnpay', 'VNPay'), ('zalopay', 'ZaloPay')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch')),
                ('status', models.CharField(choices=[('pending', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('refunded', 'Hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày thanh toán')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-payment_date'],
            },
        ),
    ]
