# Generated by Django 5.2 on 2025-05-12 12:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('is_branch_manager', models.BooleanField(default=False, verbose_name='Quản lý chi nhánh')),
                ('is_sales_staff', models.BooleanField(default=False, verbose_name='Nhân viên bán hàng')),
                ('is_inventory_staff', models.BooleanField(default=False, verbose_name='Nhân viên kho')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Tên công ty')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Điểm tích lũy')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Khách hàng VIP')),
            ],
            options={
                'verbose_name': 'Thông tin khách hàng',
                'verbose_name_plural': 'Thông tin khách hàng',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('city', models.CharField(max_length=100, verbose_name='Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
            ],
            options={
                'verbose_name': 'Địa chỉ giao hàng',
                'verbose_name_plural': 'Địa chỉ giao hàng',
            },
        ),
    ]
