# Generated by Django 5.2 on 2025-05-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authentication_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Mức độ xác thực'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_dashboard_visit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lần truy cập dashboard cuối'),
        ),
        migrations.AddField(
            model_name='user',
            name='require_password_change',
            field=models.BooleanField(default=False, verbose_name='Yêu cầu đổi mật khẩu'),
        ),
    ]
