# Generated by Django 5.2 on 2025-05-13 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhà cung cấp')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Người liên hệ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('RECEIVED', 'Đã nhận hàng'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xác nhận')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày nhận hàng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên tạo đơn')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='suppliers.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Đơn đặt hàng',
                'verbose_name_plural': 'Đơn đặt hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Thành tiền')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sản phẩm')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchaseorder', verbose_name='Đơn đặt hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn đặt hàng',
                'verbose_name_plural': 'Chi tiết đơn đặt hàng',
            },
        ),
    ]
