# Generated by Django 5.2 on 2025-05-13 16:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng')),
                ('min_quantity', models.PositiveIntegerField(default=5, verbose_name='Số lượng tối thiểu')),
                ('max_quantity', models.PositiveIntegerField(default=100, verbose_name='Số lượng tối đa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('movement_type', models.CharField(choices=[('IN', 'Nhập kho'), ('OUT', 'Xuất kho'), ('TRANSFER', 'Chuyển kho'), ('ADJUSTMENT', 'Điều chỉnh'), ('RETURN', 'Trả hàng')], max_length=10, verbose_name='Loại chuyển động')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Tham chiếu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian')),
            ],
            options={
                'verbose_name': 'Chuyển động kho',
                'verbose_name_plural': 'Chuyển động kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Mã kiểm kê')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('IN_PROGRESS', 'Đang kiểm kê'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='branches.branch', verbose_name='Chi nhánh')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiếu kiểm kê',
                'verbose_name_plural': 'Phiếu kiểm kê',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng hệ thống')),
                ('actual_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng thực tế')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventory', verbose_name='Phiếu kiểm kê')),
            ],
            options={
                'verbose_name': 'Chi tiết kiểm kê',
                'verbose_name_plural': 'Chi tiết kiểm kê',
            },
        ),
    ]
