# Generated by Django 5.2 on 2025-05-13 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='branches.branch', verbose_name='Chi nhánh'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='branches.branch', verbose_name='Chi nhánh nguồn'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên thực hiện'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='branches.branch', verbose_name='Chi nhánh đích'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('inventory', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'branch')},
        ),
    ]
