# Generated by Django 5.2 on 2025-05-13 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0002_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stock',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='products.productvariant', verbose_name='Biến thể'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'variant', 'branch')},
        ),
    ]
