# Generated by Django 5.2 on 2025-05-13 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stock_unique_together_stock_variant_and_more'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='products.productvariant', verbose_name='Biến thể'),
        ),
    ]
