# Generated by Django 5.2 on 2025-05-13 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_variant'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='products.productvariant', verbose_name='Biến thể'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('inventory', 'product', 'variant')},
        ),
    ]
