# Generated by Django 5.2 on 2025-05-13 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('report_type', models.CharField(choices=[('sales', 'Báo cáo doanh số'), ('inventory', 'Báo cáo tồn kho'), ('finance', 'Báo cáo tài chính'), ('customer', 'Báo cáo khách hàng'), ('supplier', 'Báo cáo nhà cung cấp')], max_length=20, verbose_name='Loại báo cáo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('parameters', models.JSONField(default=dict, verbose_name='Tham số báo cáo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Lần chạy cuối')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Chi nhánh')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Báo cáo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian thực hiện')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('running', 'Đang chạy'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu kết quả')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Thông báo lỗi')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report', verbose_name='Báo cáo')),
            ],
            options={
                'verbose_name': 'Lần chạy báo cáo',
                'verbose_name_plural': 'Lần chạy báo cáo',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng'), ('quarterly', 'Hàng quý')], max_length=20, verbose_name='Tần suất')),
                ('recipients', models.JSONField(default=list, verbose_name='Người nhận')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('next_run', models.DateTimeField(verbose_name='Lần chạy tiếp theo')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report', verbose_name='Báo cáo')),
            ],
            options={
                'verbose_name': 'Báo cáo định kỳ',
                'verbose_name_plural': 'Báo cáo định kỳ',
            },
        ),
    ]
