# Generated by Django 5.2 on 2025-05-13 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên chi nhánh')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('opening_hours', models.CharField(blank=True, max_length=100, verbose_name='Giờ mở cửa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='Quản lý')),
            ],
            options={
                'verbose_name': 'Chi nhánh',
                'verbose_name_plural': 'Chi nhánh',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Vị trí')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='branches.branch', verbose_name='Chi nhánh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Nhân viên chi nhánh',
                'verbose_name_plural': 'Nhân viên chi nhánh',
                'unique_together': {('branch', 'user')},
            },
        ),
    ]
